---
title: "TrumpArchive 4 : les fondements moraux du discours"
author: "cb"
date: "07/11/2020"
output: html_document
bibliography : MIrM.bib
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rtweet)
library(syuzhet)
library(readr) 
library(scales) # pour affiner les échelles de ggplot
library(gridExtra) #pour associer des graph en une figure
library(reshape2) #pour faire des fichiers " longs"
library(lubridate)
library(quanteda)
library(RcppRoll)

```



Un autre dictionnaire sur les valeurs morales qui vient des sciences politiques


https://rdrr.io/github/kbenoit/quanteda.dictionaries/man/data_dictionary_MFD.html

## Annotation

```{r liwc01, eval = TRUE}
df<-readRDS("df_nrc.rds")
# the devtools package needs to be installed for this to work
#devtools::install_github("kbenoit/quanteda.dictionaries",force=TRUE)
library(quanteda.dictionaries)
test<-liwcalike(df$text,  dictionary=data_dictionary_MFD)
library(kableExtra)
kable(head(test,5))

df<-cbind(df,test)

write_rds(df,"df_nrcliwc.rds")

df<-readRDS("df_nrcliwc.rds")

```

## Evolution des valeurs morales



```{r emo01 ,fig.height=6, fig.width=9}
df$day<-as.numeric(format(df$date, "%d")) # jour
df$month<-as.numeric(format(df$date, "%m")) # mois
df$hour<-as.numeric(format(df$date, "%H")) # heure
df$Year<-as.numeric(format(df$date, "%Y")) # annnée
df$date2<-paste0(df$Year,"-",df$month,"-",df$day)
df$date2 <- as.POSIXct(strptime(df$date2, "%Y-%m-%d"))


j=60

df_emo<-df %>%group_by(date2)%>% 
  summarise(care.virtue=mean(care.virtue, na.rm=TRUE),
            care.vice=-mean(care.vice, na.rm=TRUE),
            fairness.virtue=mean(fairness.virtue, na.rm=TRUE),
            fairness.vice= -mean(fairness.vice, na.rm=TRUE),
            loyalty.virtue= mean(loyalty.virtue, na.rm=TRUE),
            loyalty.vice = -mean(loyalty.vice, na.rm=TRUE),
            authority.virtue= mean(authority.virtue, na.rm=TRUE),
            authority.vice= -mean(authority.vice, na.rm=TRUE),
            sanctity.virtue= mean(sanctity.virtue, na.rm=TRUE),
            sanctity.vice= -mean(sanctity.vice, na.rm=TRUE)
            ) %>%
  select(date2, care.virtue,care.vice,
            fairness.virtue,fairness.vice,
            loyalty.virtue,loyalty.vice,
            authority.virtue,authority.vice,
            sanctity.virtue,sanctity.vice
) %>%
  mutate(care.virtue=roll_mean(as.numeric(care.virtue),j,na.rm = FALSE,fill=NA),
         care.vice=roll_mean(as.numeric(care.vice),j,na.rm = TRUE,fill=NA),
         fairness.virtue=roll_mean(as.numeric(fairness.virtue),j,na.rm = TRUE,fill=NA),
         fairness.vice=roll_mean(as.numeric(fairness.vice),j,na.rm = TRUE,fill=NA),
         loyalty.virtue=roll_mean(as.numeric(loyalty.virtue),j,na.rm = TRUE,fill=NA),
         loyalty.vice=roll_mean(as.numeric(loyalty.vice),j,na.rm = TRUE,fill=NA),
         authority.virtue=roll_mean(as.numeric(authority.virtue),j,na.rm = TRUE,fill=NA),
         authority.vice=roll_mean(as.numeric(authority.vice),j,na.rm = TRUE,fill=NA),
         sanctity.virtue=roll_mean(as.numeric(sanctity.virtue),j,na.rm = TRUE,fill=NA),
         sanctity.vice=roll_mean(as.numeric(sanctity.vice),j,na.rm = TRUE,fill=NA)
         )

df$date2<-as.factor(df$date2)
df_emo<-melt(df_emo,id="date2")
col=c("orange3","orange1","chartreuse3","chartreuse1","skyblue3","skyblue2","grey50","grey90","purple3", "purple1")
g1<-ggplot(data = df_emo, aes(x = date2, y = value, group = variable)) +
  geom_line(aes(color=variable), size =0.8)+
  theme_minimal()+
 # geom_smooth(method = "gam",aes(color=variable))+
  labs(title ="Evolution des émotions", x=NULL, subtitle = "lissage: 60 jours",y="valeur")+
  geom_vline(xintercept = as.POSIXct("2016-11-04",format="%Y-%m-%d"), linetype="solid",color = "grey40", alpha=.5,size=3)
g1+scale_color_manual(values=col)

#ggsave("evolutionmasque1.jpg",plot=last_plot(),width = 9, height = 6)
g2<-ggplot(data = df_emo, aes(x = date2, y = value, group = variable)) +
  geom_line(aes(color=variable), size =0.8)+
  theme_minimal()+
 # geom_smooth(method = "gam",aes(color=variable))+
  labs(title ="Evolution des émotions", x=NULL, subtitle = "lissage: 60 jours",y="valeur")+
  geom_vline(xintercept = as.POSIXct("2016-11-04",format="%Y-%m-%d"), linetype="solid",color = "grey40", alpha=.5,size=3)
g2+scale_color_manual(values=col)+facet_wrap(vars(variable), ncol=4)


```

